# Generated by Django 5.2.15 on 2026-09-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('risk_category', models.CharField(blank=True, max_length=50, null=True)),
                ('alert_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('authority', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('risk_category', models.CharField(blank=True, max_length=50, null=True)),
                ('rainfall_1d', models.FloatField(blank=True, null=True)),
                ('rainfall_3d', models.FloatField(blank=True, null=True)),
                ('rainfall_15d', models.FloatField(blank=True, null=True)),
                ('soil_moisture', models.FloatField(blank=True, null=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
